# Working with Data

## Understanding scalar and vector operations

In [1]:
myVect <- 1:4

print(myVect + 1)
print(myVect - 1)
print(2 ** myVect)

[1] 2 3 4 5
[1] 0 1 2 3
[1]  2  4  8 16


In [2]:
a <- 1:4
b <- c(2, 2, 4, 4)

print(a == b)
print(a < b)

[1] FALSE  TRUE FALSE  TRUE
[1]  TRUE FALSE  TRUE FALSE


In [3]:
a <- c(TRUE, FALSE, TRUE, FALSE)
b <- c(TRUE, TRUE, FALSE, FALSE)

print(a | b)
print(a & b)
print(!a)
print(xor(a, b))

[1]  TRUE  TRUE  TRUE FALSE
[1]  TRUE FALSE FALSE FALSE
[1] FALSE  TRUE FALSE  TRUE
[1] FALSE  TRUE  TRUE FALSE


## Performing vector multiplication

In [4]:
print(myVect * myVect)
print(myVect %*% myVect)

[1]  1  4  9 16
     [,1]
[1,]   30


## Understanding basic operations

In [5]:
A <- matrix(c(1, 1, 1, 0), nrow=2)
B <- matrix(c(1, 0, 0, 1), nrow=2)
C <- A - B

print(C)

     [,1] [,2]
[1,]    0    1
[2,]    1   -1


In [6]:
print(C * -2)

     [,1] [,2]
[1,]    0   -2
[2,]   -2    2


## Performing matrix multiplication

In [7]:
X <- matrix(c(4, 5, 2, 4, 3, 3), nrow=3, byrow=TRUE)
b <- c(3, -2)

print(X %*% b)

     [,1]
[1,]    2
[2,]   -2
[3,]    3


In [8]:
B <- matrix(c(3, -2, -2, 5), nrow=2, byrow=TRUE)

print(X %*% B)

     [,1] [,2]
[1,]    2   17
[2,]   -2   16
[3,]    3    9


## Glancing at advanced matrix operations

In [9]:
A <- matrix(c(5, 1, 0, 3,-1, 2, 4, 0,-1), nrow=3, byrow=TRUE)

print(t(A))

     [,1] [,2] [,3]
[1,]    5    3    4
[2,]    1   -1    0
[3,]    0    2   -1


In [10]:
print(solve(A))

       [,1]    [,2]   [,3]
[1,] 0.0625  0.0625  0.125
[2,] 0.6875 -0.3125 -0.625
[3,] 0.2500  0.2500 -0.500


## Using vectorization effectively

In [11]:
y = c(44, 21, 37)
dim(y) <- c(3)

print(y)
print(dim(y))

[1] 44 21 37
[1] 3


In [12]:
X <- matrix(c(1.1, 1, 545, 1,
              4.6, 0, 345, 2,
              7.2, 1, 754, 3), nrow=3, byrow=TRUE)
print(X)

     [,1] [,2] [,3] [,4]
[1,]  1.1    1  545    1
[2,]  4.6    0  345    2
[3,]  7.2    1  754    3


When you use `dim()`, R uses a column filling strategy. In order the get the same result as the previous example did using `byrow=TRUE`, you must dimension the vector first, then transpose it using `t()` as shown below.

In [13]:
X <- c(1.1, 1, 545, 1, 4.6, 0, 345, 2, 7.2, 1, 754, 3)
dim(X) <- c(4, 3)
X <- t(X)
print(X)

     [,1] [,2] [,3] [,4]
[1,]  1.1    1  545    1
[2,]  4.6    0  345    2
[3,]  7.2    1  754    3


# Exploring the World of Probabilities

## Operating on probabilities

In [14]:
Sixes <- (1/6) * (1/6)
print(Sixes)

[1] 0.02777778


In [15]:
SixAndOther <- (1/6) * (1 - (1/6))
print(SixAndOther)

[1] 0.1388889


In [16]:
OtherAndSix <- (1/6) * (1 - (1/6))
print(OtherAndSix)

[1] 0.1388889


In [17]:
OneSix <- (1/6) + (1/6)
print(OneSix)

[1] 0.3333333


## Conditioning chance by Bayes’ theorem

In [18]:
Female <- 0.6 * 0.5 / 0.35
print(Female)

[1] 0.8571429


In [19]:
IsIll <- 0.99 * 0.01 / ((0.01 * 0.99) + (0.99 * 0.01))
print(IsIll)

[1] 0.5
